language: python

services:
    - docker

before_install:
    - mkdir .ssh
    - openssl aes-256-cbc -K $encrypted_6e245bcd2662_key -iv $encrypted_6e245bcd2662_iv -in id_rsa.enc -out .ssh/id_rsa -d
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker run -t mei .

script:
    - docker run --entrypoint pytest mei